### ISSUE TITLE
Containers on Firefox look bad

### ISSUE THREAD

**Issue by sarrietav-dev** [vinceliuice/Mojave-gtk-theme#172]
This is the best theme I've ever tried, but I have an issue with the Firefox theme.
One of the best features of Firefox are containers, and when I open one, it looks like this:
![image](https://user-images.githubusercontent.com/25210925/94946727-2c565300-04a2-11eb-8151-45019466031c.png)

I don't know if it can be fixed, but I hope so!

**Comment by vinceliuice** [comment]
What's your firefox version?

**Comment by sarrietav-dev** [comment]
81.0 64-bit

**Comment by waimus** [comment]
I have the fix for that, specifically on `firefox/chrome/Mojave/parts/tabsbar.css`. These are just 3 line modifications.

In line 266 & 275, removed the circle and centres the content:
``` css
/* Create new container tab indicator */
.tabbrowser-tab[class*="identity-color-"] .tab-content::before {
	content: "";
	display: block;
	background-image: var(#userContext-icons:--identity-icon);
	background: transparent;	/* was: background: var( --identity-tab-color); */
	-moz-context-properties: fill;
	fill: var(--identity-icon-color);
	background-size: contain;
	background-repeat: no-repeat;
	background-position: center center;
	min-width: 10px;
	height: 10px;
	margin-right: 5px;
	margin-left: 0px;		/* was: margin-left: auto !important; */
	border-radius: 100%;
}
```

And line 194, I reduced the border thickness to 2px (optional):

``` css
.tabbrowser-tab[usercontextid] > .tab-stack > .tab-background {
	border-top: 2px solid var(--identity-tab-color) !important;
}
```
Now the tab looks like this:
![Screenshot from 2021-03-23 16-38-08](https://user-images.githubusercontent.com/16229430/112125588-80bdce00-8bbb-11eb-9055-4e18c19e20df.png)

Here's my fork, you can get the `firefox` folder to fix this issue.
https://github.com/waimus/Mojave-gtk-theme/tree/master/src/other/firefox

I don't intend to do a pull request because my fork of the whole theme would be too different for the original theme. But if it is possible to do a partial merge, I'm not sure because I am pretty new to git and forking projects.
