### ISSUE TITLE
[Question] How to hide the close/min/max buttons of Firefox in maximized windows ?

### ISSUE THREAD

**Issue by trmdi** [vinceliuice/Mojave-gtk-theme#62]
The title says it all. I want to hide them in maximized windows and all other elements (toolbar buttons, address bar) float to the left.
Thank you!

![image](https://user-images.githubusercontent.com/11857205/66702059-890aac00-ed2d-11e9-9f9b-801185be0dd5.png)

**Comment by vinceliuice** [comment]
Sorry this can't make it, firfox don't support this

**Comment by trmdi** [comment]
The best workaround I could found is to hide those buttons, drop it here in case someone else need it. Add this to your `customChrome.css`:

```CSS
:root[tabsintitlebar][sizemode="maximized"] #titlebar .titlebar-buttonbox-container {
    display: none;
}
````
